version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules # Prevent host's node_modules from overwriting container's
    environment:
      # Required for hot-reloading in some Docker setups
      - CHOKIDAR_USEPOLLING=true
