services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # Required for hot-reloading in some Docker setups
      - CHOKIDAR_USEPOLLING=true
